// src/lib/components/NavLinks.svelte
<script lang="ts">
  import { cn } from "$lib/utils";

  let {
    links,
    class: className = "",
    hoverBackground = true,
  }: {
    links: { label: string; href: string }[];
    class?: string;
    hoverBackground?: boolean;
  } = $props();
</script>

{#each links as { label, href } (label)}
  <a
    {href}
    class={cn(
      "relative -mx-3 -my-2 rounded-lg px-3 py-2 text-sm opacity-70 transition-colors delay-150 hover:opacity-90 hover:delay-0",
      hoverBackground && "hover:bg-neutral-500/20 transition-[background-color,opacity]",
      className
    )}
  >
    <span class="relative z-10">{label}</span>
  </a>
{/each}

// components/NavLinks.tsx
"use client";

import { useRef, useState } from "react";
import Link from "next/link";
import { AnimatePresence, motion } from "framer-motion";
import { cn } from "@/lib/utils";

export function NavLinks({
  links,
  className,
}: {
  links: {
    label: string;
    href: string;
  }[];
  className?: string;
}) {
  const [hoveredIndex, setHoveredIndex] = useState<number | null>(null);
  const timeoutRef = useRef<number | null>(null);

  return links.map(({ label, href }, index) => (
    <Link
      key={label}
      href={href}
      className={cn(
        "relative -mx-3 -my-2 rounded-lg px-3 py-2 text-sm opacity-70 transition-colors delay-150 hover:opacity-90 hover:delay-0",
        className
      )}
      onMouseEnter={() => {
        if (timeoutRef.current) {
          window.clearTimeout(timeoutRef.current);
        }
        setHoveredIndex(index);
      }}
      onMouseLeave={() => {
        timeoutRef.current = window.setTimeout(() => {
          setHoveredIndex(null);
        }, 200);
      }}
    >
      <AnimatePresence>
        {hoveredIndex === index && (
          <motion.span
            className="absolute inset-0 rounded-lg bg-neutral-500/20"
            layoutId="hoverBackground"
            initial={{ opacity: 0 }}
            animate={{ opacity: 1, transition: { duration: 0.15 } }}
            exit={{
              opacity: 0,
              transition: { duration: 0.15 },
            }}
          />
        )}
      </AnimatePresence>
      <span className="relative z-10">{label}</span>
    </Link>
  ));
}
