// src/lib/components/magicui/AnimatedList.svelte
<script lang="ts" generics="T">
  import { onMount, type Snippet } from "svelte";
  import { scale } from "svelte/transition";
  import { cn } from "$lib/utils";

  let {
    items,
    item,
    class: className = "",
    delay = 1000,
  }: {
    items: T[];
    item: Snippet<[T]>;
    class?: string;
    delay?: number;
  } = $props();

  let index = $state(0);

  onMount(() => {
    const interval = setInterval(() => {
      if (index < items.length - 1) {
        index = (index + 1) % items.length;
      } else {
        clearInterval(interval);
      }
    }, delay);
    return () => clearInterval(interval);
  });

  const itemsToShow = $derived(
    items
      .slice(0, index + 1)
      .map((value, i) => ({ value, key: i }))
      .reverse()
  );
</script>

<div class={cn("flex flex-col items-center gap-4", className)}>
  {#each itemsToShow as entry (entry.key)}
    <div
      class="mx-auto w-full origin-top"
      in:scale={{ duration: 350, start: 0 }}
    >
      {@render item(entry.value)}
    </div>
  {/each}
</div>

// components/magicui/animated-list.tsx
"use client";

import { cn } from "@/lib/utils";
import { AnimatePresence, motion } from "motion/react";
import React, {
  ComponentPropsWithoutRef,
  useEffect,
  useMemo,
  useState,
} from "react";

export function AnimatedListItem({ children }: { children: React.ReactNode }) {
  const animations = {
    initial: { scale: 0, opacity: 0 },
    animate: { scale: 1, opacity: 1, originY: 0 },
    exit: { scale: 0, opacity: 0 },
    transition: { type: "spring" as const, stiffness: 350, damping: 40 },
  };

  return (
    <motion.div {...animations} layout className="mx-auto w-full">
      {children}
    </motion.div>
  );
}

export interface AnimatedListProps extends ComponentPropsWithoutRef<"div"> {
  children: React.ReactNode;
  delay?: number;
}

export const AnimatedList = React.memo(
  ({ children, className, delay = 1000, ...props }: AnimatedListProps) => {
    const [index, setIndex] = useState(0);
    const childrenArray = useMemo(
      () => React.Children.toArray(children),
      [children]
    );

    useEffect(() => {
      if (index < childrenArray.length - 1) {
        const timeout = setTimeout(() => {
          setIndex((prevIndex) => (prevIndex + 1) % childrenArray.length);
        }, delay);

        return () => clearTimeout(timeout);
      }
    }, [index, delay, childrenArray.length]);

    const itemsToShow = useMemo(() => {
      const result = childrenArray.slice(0, index + 1).reverse();
      return result;
    }, [index, childrenArray]);

    return (
      <div
        className={cn(`flex flex-col items-center gap-4`, className)}
        {...props}
      >
        <AnimatePresence>
          {itemsToShow.map((item) => (
            <AnimatedListItem key={(item as React.ReactElement).key}>
              {item}
            </AnimatedListItem>
          ))}
        </AnimatePresence>
      </div>
    );
  }
);

AnimatedList.displayName = "AnimatedList";
