// src/routes/[lang=lang]/(main)/subscription/[slug]/+page.svelte
<script lang="ts">
  import Breadcrumb from "$lib/components/Breadcrumb.svelte";
  import StoreDownloadLinks from "$lib/components/StoreDownloadLinks.svelte";
  import { getAppStoreLink } from "$lib/constants";
  import { localizeUrl, uiDictionary, type Language } from "$lib/i18n";
  import type { PageProps } from "./$types";

  let { data }: PageProps = $props();

  const lang = $derived(data.lang as Language);
  const t = $derived(uiDictionary[lang].subscription);
  const appStoreLink = $derived(getAppStoreLink(["subscription", "page", lang]));
</script>

<div class="relative isolate px-6 pt-14 lg:px-8">
  <Breadcrumb {lang} />
  <div class="mx-auto max-w-2xl py-32 sm:py-42 lg:py-52">
    {#if data.channel}
      <div
        class="flex flex-col rounded-lg border bg-white p-4 sm:p-8 dark:bg-neutral-900"
      >
        <h1
          class="flex gap-2 text-2xl font-semibold tracking-tight text-balance opacity-90"
        >
          <span
            style={`background-color: ${data.channel.color}; width: 6px; margin: 6px 0; border-radius: 6px;`}
          ></span>
          {data.channel.name}
          <span class="opacity-60">#{data.channel.id}</span>
        </h1>
        <p class="mt-2 font-medium text-pretty">{data.channel.titleTemplate}</p>
        <p class="font-medium text-pretty opacity-60">
          {data.channel.bodyTemplate}
        </p>
        {#if data.channel.note}
          <div class="mt-4 flex font-medium text-pretty opacity-60">
            <div class="mr-2 w-1 rounded-full bg-foreground"></div>
            <p>{data.channel.note}</p>
          </div>
        {/if}
      </div>
      <a
        class="mt-4 block w-full rounded-lg bg-orange-500 py-2 text-center text-white"
        href={`echobell://subscribe/${data.token}`}
      >
        {t.subscribe}
      </a>
    {:else}
      <div class="mb-20 text-center text-4xl">{t.channelNotFound}</div>
    {/if}

    <p class="mt-5">{t.subscriptionTips}</p>
    <p class="mt-2">{t.downloadTips}</p>
    <div class="mt-10 flex flex-col items-center justify-center gap-5 sm:flex-row">
      <StoreDownloadLinks appStoreImage={t.appStoreImage} {appStoreLink} />
      <a
        href={localizeUrl("/docs", lang)}
        class="text-sm/6 font-semibold opacity-90"
      >
        {t.learnMore} <span aria-hidden="true">→</span>
      </a>
    </div>
  </div>
</div>

// app/[lang]/(main)/subscription/[slug]/page.tsx
import { fetchChannelBySubscriptionToken } from "@/app/actions/channel";
import { APP_STORE_LINK } from "@/constants";
import Link from "next/link";
import Image from "next/image";

import { uiDictionary } from "@/lib/i18n";

interface SubscriptionPageProps {
  params: Promise<{
    lang: string;
    slug: string;
  }>;
}

export default async function SubscriptionPage({
  params,
}: SubscriptionPageProps) {
  const { slug: subscriptionToken, lang } = await params;
  const t = uiDictionary[lang as keyof typeof uiDictionary].subscription;
  const channel = await fetchChannelBySubscriptionToken(subscriptionToken);

  return (
    <div className="relative isolate px-6 pt-14 lg:px-8">
      <div className="mx-auto max-w-2xl py-32 sm:py-42 lg:py-52">
        {channel ? (
          <>
            <div className="flex flex-col bg-white dark:bg-neutral-900 rounded-lg p-4 sm:p-8 border">
              <h1 className="flex gap-2 text-2xl font-semibold tracking-tight text-balance opacity-90">
                <div
                  style={{
                    backgroundColor: channel.color,
                    width: "6px",
                    margin: "6px 0",
                    borderRadius: "6px",
                  }}
                />
                {channel.name}
                <span className="opacity-60">#{channel.id}</span>
              </h1>
              <p className="font-medium text-pretty mt-2">
                {channel.titleTemplate}
              </p>
              <p className="font-medium text-pretty opacity-60">
                {channel.bodyTemplate}
              </p>
              {channel.note && (
                <div className="font-medium text-pretty opacity-60 mt-4 flex">
                  <div className="w-1 rounded-full bg-foreground mr-2" />
                  <p>{channel.note}</p>
                </div>
              )}
            </div>
            <a
              className="w-full block mt-4 bg-orange-500 text-white py-2 rounded-lg text-center"
              href={`echobell://subscribe/${subscriptionToken}`}
            >
              {t.subscribe}
            </a>
          </>
        ) : (
          <div className="text-4xl text-center mb-20">{t.channelNotFound}</div>
        )}

        <p className="mt-5">{t.subscriptionTips}</p>
        <p className="mt-2">{t.downloadTips}</p>
        <div className="mt-10 flex items-center justify-center gap-x-6">
          <a href={APP_STORE_LINK} target="_blank">
            <Image src={t.appStoreImage} alt="App Store" />
          </a>
          <Link href="/docs" className="text-sm/6 font-semibold opacity-90">
            {t.learnMore} <span aria-hidden="true">→</span>
          </Link>
        </div>
      </div>
    </div>
  );
}
