// app/[lang]/(main)/features/comparisons/page.tsx
import Link from "next/link";
import { ArrowRightIcon, CheckCircle2Icon, ScaleIcon } from "lucide-react";
import type { Metadata } from "next";
import { Breadcrumb } from "@/components/Breadcrumb";
import { FeatureJsonLd } from "@/components/JsonLd";
import { Language, languages, localizeUrl } from "@/lib/i18n";
import { baseUrl, createMetadata } from "@/lib/metadata";
import { getComparisonsIndexData } from "@/lib/competitor-comparisons";
import { getAppStoreLink } from "@/constants";

const comparisonsPageUi: Record<
  Language,
  {
    breadcrumbFeaturesLabel: string;
    breadcrumbCurrentLabel: string;
    viewFullComparison: string;
  }
> = {
  en: {
    breadcrumbFeaturesLabel: "Features",
    breadcrumbCurrentLabel: "Comparisons",
    viewFullComparison: "View full comparison",
  },
  zh: {
    breadcrumbFeaturesLabel: "功能",
    breadcrumbCurrentLabel: "竞品对比",
    viewFullComparison: "查看完整对比",
  },
  es: {
    breadcrumbFeaturesLabel: "Funciones",
    breadcrumbCurrentLabel: "Comparativas",
    viewFullComparison: "Ver comparativa completa",
  },
  fr: {
    breadcrumbFeaturesLabel: "Fonctionnalités",
    breadcrumbCurrentLabel: "Comparaisons",
    viewFullComparison: "Voir la comparaison complète",
  },
  ja: {
    breadcrumbFeaturesLabel: "機能",
    breadcrumbCurrentLabel: "比較",
    viewFullComparison: "比較の全文を見る",
  },
  de: {
    breadcrumbFeaturesLabel: "Funktionen",
    breadcrumbCurrentLabel: "Vergleiche",
    viewFullComparison: "Vollständigen Vergleich ansehen",
  },
};

export default async function ComparisonsIndexPage({
  params,
}: {
  params: Promise<{ lang: Language }>;
}) {
  const { lang } = await params;
  const t = getComparisonsIndexData(lang);
  const canonical = new URL(
    localizeUrl("/features/comparisons", lang),
    baseUrl
  ).toString();
  const ui = comparisonsPageUi[lang];

  return (
    <div className="min-h-screen">
      <FeatureJsonLd
        name={t.meta.title}
        description={t.meta.description}
        url={canonical}
      />

      <div className="mx-auto max-w-7xl px-6 pt-24 lg:px-8">
        <Breadcrumb
          lang={lang}
          customItems={[
            {
              label: ui.breadcrumbFeaturesLabel,
              href: localizeUrl("/features", lang),
            },
            {
              label: ui.breadcrumbCurrentLabel,
              href: localizeUrl("/features/comparisons", lang),
              isCurrentPage: true,
            },
          ]}
        />
      </div>

      <section className="relative isolate overflow-hidden">
        <div className="mx-auto max-w-7xl px-6 py-24 sm:py-32 lg:px-8">
          <div className="mx-auto max-w-3xl text-center">
            <span className="inline-flex items-center rounded-full border border-neutral-200 bg-white px-3 py-1 text-sm font-medium text-neutral-700 dark:border-neutral-700 dark:bg-neutral-900 dark:text-neutral-200">
              <ScaleIcon className="mr-1.5 h-4 w-4" />
              {t.hero.badge}
            </span>
            <h1 className="mt-6 text-4xl font-bold tracking-tight sm:text-5xl lg:text-6xl">
              {t.hero.title}
            </h1>
            <p className="mt-6 text-xl text-neutral-600 dark:text-neutral-400">
              {t.hero.subtitle}
            </p>
            <p className="mt-4 text-lg text-neutral-500 dark:text-neutral-500">
              {t.hero.description}
            </p>
          </div>
        </div>
      </section>

      <section className="py-16 sm:py-20">
        <div className="mx-auto max-w-7xl px-6 lg:px-8">
          <div className="mx-auto max-w-3xl text-center">
            <h2 className="text-3xl font-bold tracking-tight sm:text-4xl">
              {t.cardsTitle}
            </h2>
            <p className="mt-4 text-lg text-neutral-600 dark:text-neutral-400">
              {t.cardsDescription}
            </p>
          </div>
          <div className="mx-auto mt-12 grid max-w-6xl gap-6 md:grid-cols-2 xl:grid-cols-3">
            {t.cards.map((card) => (
                <Link
                  key={card.slug}
                  href={localizeUrl(`/features/comparisons/${card.slug}`, lang)}
                  className="group rounded-2xl border border-neutral-200 bg-white p-6 shadow-sm transition-all hover:-translate-y-0.5 hover:border-neutral-300 hover:shadow-md dark:border-neutral-800 dark:bg-neutral-900 dark:hover:border-neutral-700"
                >
                  <p className="text-xs font-semibold uppercase tracking-wider text-neutral-500 dark:text-neutral-400">
                    {card.competitorName}
                  </p>
                <h3 className="mt-2 text-xl font-semibold leading-snug">
                  {card.tagline}
                </h3>
                <p className="mt-3 text-sm text-neutral-600 dark:text-neutral-400">
                  {card.summary}
                </p>
                <ul className="mt-5 space-y-2 text-sm text-neutral-600 dark:text-neutral-300">
                  {card.highlights.map((highlight, index) => (
                    <li key={index} className="flex items-start gap-2">
                      <CheckCircle2Icon className="mt-0.5 h-4 w-4 flex-shrink-0 text-orange-600 dark:text-orange-400" />
                      <span>{highlight}</span>
                    </li>
                  ))}
                </ul>
                <div className="mt-6 flex items-center text-sm font-semibold text-neutral-900 dark:text-neutral-100">
                  {ui.viewFullComparison}
                  <ArrowRightIcon className="ml-2 h-4 w-4 transition-transform group-hover:translate-x-1" />
                </div>
              </Link>
            ))}
          </div>
        </div>
      </section>

      <section className="bg-neutral-50/70 py-24 dark:bg-neutral-900/40">
        <div className="mx-auto max-w-7xl px-6 lg:px-8">
          <div className="mx-auto max-w-3xl text-center">
            <h2 className="text-3xl font-bold tracking-tight sm:text-4xl">
              {t.methodology.title}
            </h2>
            <p className="mt-4 text-lg text-neutral-600 dark:text-neutral-400">
              {t.methodology.description}
            </p>
          </div>
          <div className="mx-auto mt-12 grid max-w-5xl gap-6 sm:grid-cols-2">
            {t.methodology.items.map((item, index) => (
              <div
                key={index}
                className="rounded-2xl border border-neutral-200 bg-white p-6 dark:border-neutral-800 dark:bg-neutral-900"
              >
                <h3 className="text-lg font-semibold">{item.title}</h3>
                <p className="mt-2 text-sm text-neutral-600 dark:text-neutral-400">
                  {item.description}
                </p>
              </div>
            ))}
          </div>
        </div>
      </section>

      <section className="border-t border-neutral-200 py-24 dark:border-neutral-800">
        <div className="mx-auto max-w-7xl px-6 lg:px-8">
          <div className="mx-auto max-w-2xl text-center">
            <h2 className="text-3xl font-bold tracking-tight sm:text-4xl">
              {t.cta.title}
            </h2>
            <p className="mt-4 text-lg text-neutral-600 dark:text-neutral-400">
              {t.cta.description}
            </p>
            <div className="mt-10 flex flex-col items-center justify-center gap-4 sm:flex-row">
              <Link
                href={getAppStoreLink(["features", "comparisons", "cta", lang])}
                target="_blank"
                className="rounded-full bg-orange-600 px-6 py-3 text-sm font-semibold text-white transition-colors hover:bg-orange-500"
              >
                {t.cta.primary}
              </Link>
              <Link
                href={localizeUrl("/docs", lang)}
                className="rounded-full border border-neutral-300 px-6 py-3 text-sm font-semibold transition-colors hover:border-neutral-400 dark:border-neutral-700 dark:hover:border-neutral-600"
              >
                {t.cta.secondary}
              </Link>
            </div>
          </div>
        </div>
      </section>
    </div>
  );
}

export async function generateMetadata({
  params,
}: {
  params: Promise<{ lang: Language }>;
}): Promise<Metadata> {
  const { lang } = await params;
  const t = getComparisonsIndexData(lang);
  const canonical = new URL(
    localizeUrl("/features/comparisons", lang),
    baseUrl
  ).toString();

  const ogImageParams = new URLSearchParams({
    title: t.meta.title,
    description: t.meta.description,
    type: "default",
    lang,
  });
  const ogImageUrl = new URL(
    `/api/og?${ogImageParams.toString()}`,
    baseUrl
  ).toString();

  return createMetadata({
    title: t.meta.title,
    description: t.meta.description,
    keywords: t.meta.keywords,
    alternates: {
      canonical,
      languages: {
        "x-default": localizeUrl("/features/comparisons", "en"),
        ...Object.fromEntries(
          languages.map((l) => [l, localizeUrl("/features/comparisons", l)])
        ),
      },
    },
    openGraph: {
      url: canonical,
      images: [
        {
          url: ogImageUrl,
          width: 1200,
          height: 630,
          alt: t.meta.title,
        },
      ],
    },
    twitter: {
      images: [{ url: ogImageUrl, alt: t.meta.title }],
    },
  });
}

// src/routes/[lang=lang]/(main)/features/comparisons/+page.svelte
<script lang="ts">
  import { ArrowRight, CircleCheck, Scale } from "@lucide/svelte";
  import Breadcrumb from "$lib/components/Breadcrumb.svelte";
  import JsonLd from "$lib/components/JsonLd.svelte";
  import { featureJsonLd } from "$lib/jsonld";
  import { toAbsoluteUrl } from "$lib/metadata";
  import { getAppStoreLink, getGooglePlayLink } from "$lib/constants";
  import { localizeUrl, type Language } from "$lib/i18n";
  import { getComparisonsIndexData } from "$lib/competitor-comparisons";
  import type { PageProps } from "./$types";

  let { data }: PageProps = $props();

  const lang = $derived(data.lang as Language);
  const t = $derived(getComparisonsIndexData(lang));
  const canonical = $derived(
    toAbsoluteUrl(localizeUrl("/features/comparisons", lang))
  );

  const comparisonsPageUi: Record<
    Language,
    {
      breadcrumbFeaturesLabel: string;
      breadcrumbCurrentLabel: string;
      viewFullComparison: string;
    }
  > = {
    en: {
      breadcrumbFeaturesLabel: "Features",
      breadcrumbCurrentLabel: "Comparisons",
      viewFullComparison: "View full comparison",
    },
    zh: {
      breadcrumbFeaturesLabel: "功能",
      breadcrumbCurrentLabel: "竞品对比",
      viewFullComparison: "查看完整对比",
    },
    es: {
      breadcrumbFeaturesLabel: "Funciones",
      breadcrumbCurrentLabel: "Comparativas",
      viewFullComparison: "Ver comparativa completa",
    },
    fr: {
      breadcrumbFeaturesLabel: "Fonctionnalités",
      breadcrumbCurrentLabel: "Comparaisons",
      viewFullComparison: "Voir la comparaison complète",
    },
    ja: {
      breadcrumbFeaturesLabel: "機能",
      breadcrumbCurrentLabel: "比較",
      viewFullComparison: "比較の全文を見る",
    },
    de: {
      breadcrumbFeaturesLabel: "Funktionen",
      breadcrumbCurrentLabel: "Vergleiche",
      viewFullComparison: "Vollständigen Vergleich ansehen",
    },
  };

  const ui = $derived(comparisonsPageUi[lang]);
</script>

<div class="min-h-screen">
  <JsonLd
    data={featureJsonLd({
      name: t.meta.title,
      description: t.meta.description,
      url: canonical,
    })}
  />

  <div class="mx-auto max-w-7xl px-6 pt-24 lg:px-8">
    <Breadcrumb
      {lang}
      customItems={[
        {
          label: ui.breadcrumbFeaturesLabel,
          href: localizeUrl("/features", lang),
        },
        {
          label: ui.breadcrumbCurrentLabel,
          href: localizeUrl("/features/comparisons", lang),
          isCurrentPage: true,
        },
      ]}
    />
  </div>

  <section class="relative isolate overflow-hidden">
    <div class="mx-auto max-w-7xl px-6 py-24 sm:py-32 lg:px-8">
      <div class="mx-auto max-w-3xl text-center">
        <span
          class="inline-flex items-center rounded-full bg-orange-100 px-3 py-1 text-sm font-medium text-orange-700 dark:bg-orange-900/30 dark:text-orange-400"
        >
          <Scale class="mr-1.5 h-4 w-4" />
          {t.hero.badge}
        </span>
        <h1
          class="mt-6 text-4xl font-semibold tracking-tight text-balance opacity-90 sm:text-5xl lg:text-6xl"
        >
          {t.hero.title}
        </h1>
        <p class="mt-6 text-xl opacity-60">{t.hero.subtitle}</p>
        <p class="mt-4 text-lg opacity-50">{t.hero.description}</p>
      </div>
    </div>
  </section>

  <section class="py-16 sm:py-20">
    <div class="mx-auto max-w-7xl px-6 lg:px-8">
      <div class="mx-auto max-w-3xl text-center">
        <h2 class="text-3xl font-semibold tracking-tight opacity-90 sm:text-4xl">
          {t.cardsTitle}
        </h2>
        <p class="mt-4 text-lg opacity-60">{t.cardsDescription}</p>
      </div>
      <div class="mx-auto mt-12 grid max-w-6xl gap-6 md:grid-cols-2 xl:grid-cols-3">
        {#each t.cards as card (card.slug)}
          <div class="relative flex">
            <div
              class="absolute inset-px rounded-3xl bg-neutral-50 dark:bg-neutral-900/50"
            ></div>
            <a
              href={localizeUrl(`/features/comparisons/${card.slug}`, lang)}
              class="group relative flex w-full flex-col overflow-hidden rounded-3xl p-8 transition-all hover:-translate-y-1"
            >
              <p
                class="text-xs font-semibold tracking-wider text-orange-600 uppercase dark:text-orange-400"
              >
                {card.competitorName}
              </p>
              <h3 class="mt-2 text-xl leading-snug font-semibold tracking-tight opacity-90">
                {card.tagline}
              </h3>
              <p class="mt-3 text-sm/6 opacity-60">{card.summary}</p>
              <ul class="mt-5 space-y-2 text-sm opacity-70">
                {#each card.highlights as highlight (highlight)}
                  <li class="flex items-start gap-2">
                    <CircleCheck
                      class="mt-0.5 h-4 w-4 flex-shrink-0 text-orange-600 dark:text-orange-400"
                    />
                    <span>{highlight}</span>
                  </li>
                {/each}
              </ul>
              <div
                class="mt-auto flex items-center pt-6 text-sm font-semibold text-orange-600 dark:text-orange-400"
              >
                {ui.viewFullComparison}
                <ArrowRight
                  class="ml-2 h-4 w-4 transition-transform group-hover:translate-x-1"
                />
              </div>
            </a>
            <div
              class="pointer-events-none absolute inset-px rounded-3xl ring-1 shadow-sm ring-black/5"
            ></div>
          </div>
        {/each}
      </div>
    </div>
  </section>

  <section class="py-24">
    <div class="mx-auto max-w-7xl px-6 lg:px-8">
      <div class="mx-auto max-w-3xl text-center">
        <h2 class="text-3xl font-semibold tracking-tight opacity-90 sm:text-4xl">
          {t.methodology.title}
        </h2>
        <p class="mt-4 text-lg opacity-60">{t.methodology.description}</p>
      </div>
      <div class="mx-auto mt-12 grid max-w-5xl gap-6 sm:grid-cols-2">
        {#each t.methodology.items as item (item.title)}
          <div class="relative flex">
            <div
              class="absolute inset-px rounded-3xl bg-neutral-50 dark:bg-neutral-900/50"
            ></div>
            <div class="relative w-full rounded-3xl p-6">
              <h3 class="text-lg font-semibold tracking-tight opacity-90">
                {item.title}
              </h3>
              <p class="mt-2 text-sm/6 opacity-60">{item.description}</p>
            </div>
            <div
              class="pointer-events-none absolute inset-px rounded-3xl ring-1 shadow-sm ring-black/5"
            ></div>
          </div>
        {/each}
      </div>
    </div>
  </section>

  <section class="border-t border-neutral-200 py-24 dark:border-neutral-800">
    <div class="mx-auto max-w-7xl px-6 lg:px-8">
      <div class="mx-auto max-w-2xl text-center">
        <h2 class="text-3xl font-semibold tracking-tight opacity-90 sm:text-4xl">
          {t.cta.title}
        </h2>
        <p class="mt-4 text-lg opacity-60">{t.cta.description}</p>
        <div class="mt-10 flex flex-col items-center justify-center gap-4 sm:flex-row">
          <a
            href={getAppStoreLink(["features", "comparisons", "cta", lang])}
            target="_blank"
            rel="noopener noreferrer"
            class="rounded-full bg-orange-600 px-6 py-3 text-sm font-semibold text-white transition-colors hover:bg-orange-500"
          >
            {t.cta.primary}
          </a>
          <a
            href={getGooglePlayLink()}
            target="_blank"
            rel="noopener noreferrer"
            class="rounded-full border border-neutral-300 px-6 py-3 text-sm font-semibold transition-colors hover:border-neutral-400 dark:border-neutral-700 dark:hover:border-neutral-600"
          >
            Google Play
          </a>
          <a
            href={localizeUrl("/docs", lang)}
            class="rounded-full border border-neutral-300 px-6 py-3 text-sm font-semibold transition-colors hover:border-neutral-400 dark:border-neutral-700 dark:hover:border-neutral-600"
          >
            {t.cta.secondary}
          </a>
        </div>
      </div>
    </div>
  </section>
</div>
