// app/(main)/subscription/[slug]/page.tsx
import { fetchChannelBySubscriptionToken } from "@/app/actions/channel";
import { notFound } from "next/navigation";
import { APP_STORE_LINK } from '@/constants';
import Link from 'next/link'
import Image from 'next/image';

import AppStore from '@/public/images/app-store.en.svg';

export default async function SubscriptionPage({
  params,
}: {
  params: { slug: string };
}) {
  const { slug: subscriptionToken } = params;
  const channel = await fetchChannelBySubscriptionToken(subscriptionToken);

  if (!channel) {
    notFound();
  }

  return (
    <div className="relative isolate px-6 pt-14 lg:px-8">
        <div
          aria-hidden="true"
          className="absolute inset-x-0 -top-40 -z-10 transform-gpu overflow-hidden blur-3xl sm:-top-80"
        >
          <div
            style={{
              clipPath:
                'polygon(74.1% 44.1%, 100% 61.6%, 97.5% 26.9%, 85.5% 0.1%, 80.7% 2%, 72.5% 32.5%, 60.2% 62.4%, 52.4% 68.1%, 47.5% 58.3%, 45.2% 34.5%, 27.5% 76.7%, 0.1% 64.9%, 17.9% 100%, 27.6% 76.8%, 76.1% 97.7%, 74.1% 44.1%)',
            }}
            className="dark:hidden relative left-[calc(50%-11rem)] aspect-1155/678 w-[36.125rem] -translate-x-1/2 rotate-[30deg] bg-linear-to-tr from-[#ff80b5] to-orange-400 opacity-30 sm:left-[calc(50%-30rem)] sm:w-[72.1875rem]"
          />
        </div>
        <div className="mx-auto max-w-2xl py-32 sm:py-48 lg:py-56">
          <div className="flex flex-col">
            <h1 className="text-2xl font-semibold tracking-tight text-balance opacity-90 sm:text-7xl">
            {channel.name}<span className="opacity-60">#{channel.id}</span>
            </h1>
            <p className="mt-8 text-lg font-medium text-pretty sm:text-xl/8">
              {channel.titleTemplate}
            </p>
            <p className="mt-8 text-lg font-medium text-pretty opacity-60 sm:text-xl/8">
              {channel.bodyTemplate}
            </p>
            <div className="mt-10 flex items-center justify-center gap-x-6">
              <a
                href={APP_STORE_LINK}
                target="_blank"
              >
                <Image src={AppStore} alt="App Store" />
              </a>
              <Link href="/docs" className="text-sm/6 font-semibold opacity-90">
                Documentation <span aria-hidden="true">→</span>
              </Link>
            </div>
          </div>
        </div>
        <div
          aria-hidden="true"
          className="absolute inset-x-0 top-[calc(100%-13rem)] -z-10 transform-gpu overflow-hidden blur-3xl sm:top-[calc(100%-30rem)]"
        >
          <div
            style={{
              clipPath:
                'polygon(74.1% 44.1%, 100% 61.6%, 97.5% 26.9%, 85.5% 0.1%, 80.7% 2%, 72.5% 32.5%, 60.2% 62.4%, 52.4% 68.1%, 47.5% 58.3%, 45.2% 34.5%, 27.5% 76.7%, 0.1% 64.9%, 17.9% 100%, 27.6% 76.8%, 76.1% 97.7%, 74.1% 44.1%)',
            }}
            className="dark:hidden relative left-[calc(50%+3rem)] aspect-1155/678 w-[36.125rem] -translate-x-1/2 bg-linear-to-tr from-[#ff80b5] to-[#9089fc] opacity-30 sm:left-[calc(50%+36rem)] sm:w-[72.1875rem]"
          />
        </div>
      </div>
  );
}

// src/routes/[lang=lang]/(main)/subscription/[slug]/+page.svelte
<script lang="ts">
  import Breadcrumb from "$lib/components/Breadcrumb.svelte";
  import StoreDownloadLinks from "$lib/components/StoreDownloadLinks.svelte";
  import { getAppStoreLink } from "$lib/constants";
  import { localizeUrl, uiDictionary, type Language } from "$lib/i18n";
  import type { PageProps } from "./$types";

  let { data }: PageProps = $props();

  const lang = $derived(data.lang as Language);
  const t = $derived(uiDictionary[lang].subscription);
  const appStoreLink = $derived(getAppStoreLink(["subscription", "page", lang]));
</script>

<div class="relative isolate px-6 pt-14 lg:px-8">
  <Breadcrumb {lang} />
  <div class="mx-auto max-w-2xl py-32 sm:py-42 lg:py-52">
    {#if data.channel}
      <div
        class="flex flex-col rounded-lg border bg-white p-4 sm:p-8 dark:bg-neutral-900"
      >
        <h1
          class="flex gap-2 text-2xl font-semibold tracking-tight text-balance opacity-90"
        >
          <span
            style={`background-color: ${data.channel.color}; width: 6px; margin: 6px 0; border-radius: 6px;`}
          ></span>
          {data.channel.name}
          <span class="opacity-60">#{data.channel.id}</span>
        </h1>
        <p class="mt-2 font-medium text-pretty">{data.channel.titleTemplate}</p>
        <p class="font-medium text-pretty opacity-60">
          {data.channel.bodyTemplate}
        </p>
        {#if data.channel.note}
          <div class="mt-4 flex font-medium text-pretty opacity-60">
            <div class="mr-2 w-1 rounded-full bg-foreground"></div>
            <p>{data.channel.note}</p>
          </div>
        {/if}
      </div>
      <a
        class="mt-4 block w-full rounded-lg bg-orange-500 py-2 text-center text-white"
        href={`echobell://subscribe/${data.token}`}
      >
        {t.subscribe}
      </a>
    {:else}
      <div class="mb-20 text-center text-4xl">{t.channelNotFound}</div>
    {/if}

    <p class="mt-5">{t.subscriptionTips}</p>
    <p class="mt-2">{t.downloadTips}</p>
    <div class="mt-10 flex flex-col items-center justify-center gap-5 sm:flex-row">
      <StoreDownloadLinks appStoreImage={t.appStoreImage} {appStoreLink} />
      <a
        href={localizeUrl("/docs", lang)}
        class="text-sm/6 font-semibold opacity-90"
      >
        {t.learnMore} <span aria-hidden="true">→</span>
      </a>
    </div>
  </div>
</div>
