// app/[lang]/(main)/blog/[slug]/page.tsx
import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { InlineTOC } from "fumadocs-ui/components/inline-toc";
import defaultMdxComponents from "fumadocs-ui/mdx";
import { blog } from "@/lib/source";
import { File, Files, Folder } from "fumadocs-ui/components/files";
import { Tab, Tabs } from "fumadocs-ui/components/tabs";
import { Language, uiDictionary } from "@/lib/i18n";
import { displayDate } from "@/lib/date";

export default async function Page(props: {
  params: Promise<{ lang: Language; slug: string }>;
}) {
  const params = await props.params;
  const page = blog.getPage([params.slug], params.lang);
  const t = uiDictionary[params.lang].blog;

  if (!page) notFound();

  const Mdx = page.data.body;
  const toc = page.data.toc;

  return (
    <div className="relative isolate px-6 py-24 sm:py-32 lg:px-8">
      <div className="mx-auto max-w-7xl">
        <div className="container px-0">
          <h2 className="text-4xl font-semibold tracking-tight text-pretty opacity-90 sm:text-5xl">
            {page.data.title}
          </h2>
          <p className="mt-2 text-lg/8 opacity-60">{page.data.description}</p>
        </div>
        <article className="container flex flex-col px-0 py-8 lg:flex-row">
          <div className="prose min-w-0 flex-1 lg:pr-8">
            <InlineTOC className="mb-8" items={toc} />
            <Mdx
              components={{
                ...defaultMdxComponents,
                File,
                Files,
                Folder,
                Tabs,
                Tab,
              }}
            />
          </div>
          <div className="flex flex-col gap-4 border-l p-4 text-sm lg:w-[250px]">
            <div>
              <p className="mb-1 text-fd-muted-foreground">{t.writtenBy}</p>
              <p className="font-medium">{page.data.author}</p>
            </div>
            <div>
              <p className="mb-1 text-sm text-fd-muted-foreground">{t.at}</p>
              <p className="font-medium">
                {displayDate(
                  new Date(page.data.date ?? page.file.name),
                  params.lang
                )}
              </p>
            </div>
          </div>
        </article>
      </div>
    </div>
  );
}

export async function generateMetadata(props: {
  params: Promise<{ lang: Language; slug: string }>;
}): Promise<Metadata> {
  const params = await props.params;
  const page = blog.getPage([params.slug], params.lang);

  if (!page) notFound();

  return {
    title: page.data.title,
    description:
      page.data.description ?? "The library for building documentation sites",
  };
}

// src/routes/[lang=lang]/(main)/subscription/[slug]/+page.svelte
<script lang="ts">
  import Breadcrumb from "$lib/components/Breadcrumb.svelte";
  import StoreDownloadLinks from "$lib/components/StoreDownloadLinks.svelte";
  import { getAppStoreLink } from "$lib/constants";
  import { localizeUrl, uiDictionary, type Language } from "$lib/i18n";
  import type { PageProps } from "./$types";

  let { data }: PageProps = $props();

  const lang = $derived(data.lang as Language);
  const t = $derived(uiDictionary[lang].subscription);
  const appStoreLink = $derived(getAppStoreLink(["subscription", "page", lang]));
</script>

<div class="relative isolate px-6 pt-14 lg:px-8">
  <Breadcrumb {lang} />
  <div class="mx-auto max-w-2xl py-32 sm:py-42 lg:py-52">
    {#if data.channel}
      <div
        class="flex flex-col rounded-lg border bg-white p-4 sm:p-8 dark:bg-neutral-900"
      >
        <h1
          class="flex gap-2 text-2xl font-semibold tracking-tight text-balance opacity-90"
        >
          <span
            style={`background-color: ${data.channel.color}; width: 6px; margin: 6px 0; border-radius: 6px;`}
          ></span>
          {data.channel.name}
          <span class="opacity-60">#{data.channel.id}</span>
        </h1>
        <p class="mt-2 font-medium text-pretty">{data.channel.titleTemplate}</p>
        <p class="font-medium text-pretty opacity-60">
          {data.channel.bodyTemplate}
        </p>
        {#if data.channel.note}
          <div class="mt-4 flex font-medium text-pretty opacity-60">
            <div class="mr-2 w-1 rounded-full bg-foreground"></div>
            <p>{data.channel.note}</p>
          </div>
        {/if}
      </div>
      <a
        class="mt-4 block w-full rounded-lg bg-orange-500 py-2 text-center text-white"
        href={`echobell://subscribe/${data.token}`}
      >
        {t.subscribe}
      </a>
    {:else}
      <div class="mb-20 text-center text-4xl">{t.channelNotFound}</div>
    {/if}

    <p class="mt-5">{t.subscriptionTips}</p>
    <p class="mt-2">{t.downloadTips}</p>
    <div class="mt-10 flex flex-col items-center justify-center gap-5 sm:flex-row">
      <StoreDownloadLinks appStoreImage={t.appStoreImage} {appStoreLink} />
      <a
        href={localizeUrl("/docs", lang)}
        class="text-sm/6 font-semibold opacity-90"
      >
        {t.learnMore} <span aria-hidden="true">→</span>
      </a>
    </div>
  </div>
</div>
